# Site settings
title: NeoAntropofagia
description: Viva a mistura, o respeito e a alegria!
url: "http://www.neoantropofagia.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Mauricio Urraco
user_title: Viva a mistura, o respeito e a alegria!

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
